version: '3.3'
services:


  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net
      - front_net
  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    command:
      - '--mongodb.uri=mongodb://post_db:27017'
    networks:
      - back_net

  blackbox-exporter:
    image: quay.io/prometheus/blackbox-exporter:latest
    networks:
      - back_net

  mongo_db:
    image: mongo:${DB_VER}
    volumes:
      - post_db:${DB_PATH}
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VER}
    networks:
      - back_net
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
      - back_net
      - front_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - back_net
      - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24

